public class day1_types {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
        /*
                System.out.println(args[0]);
        for (int i = 0; i < args.length; i++) {
            System.out.println(args[i]);
            int _a = 10;
            System.out.println(_a);
        */
// data types and their range and precision
            byte num=Byte.MAX_VALUE;
            byte num1=Byte.MIN_VALUE;
            System.out.println(num + ", " + num1);    
            System.out.println((byte)1920);
            short a=Short.MAX_VALUE;
            short b=Short.MIN_VALUE;
            System.out.println(a + ", " + b);
            long c=Long.MAX_VALUE;
            long d=Long.MIN_VALUE;
            System.out.println(c + ", " + d);
            int x=Integer.MAX_VALUE;
            int y=Integer.MIN_VALUE;
            System.out.println(x + ", " + y);
            char e=Character.MAX_VALUE;
            char f=Character.MIN_VALUE;
            System.out.println((int)e + ", " + (int)f);
            float g=Float.MAX_VALUE;
            float h=Float.MIN_VALUE;
            System.out.println(g + ", " + h);
            double i=Double.MAX_VALUE;
            double j=Double.MIN_VALUE;  
            System.out.println(i + ", " + j);
            // char tests
                char ch1 = 'A';
                char ch2=97;
                char ch3=51;
                System.out.println(ch1 + ", " + ch2 + ", " + ch3);

            // implicit type casting
            char ch4 = 'A';
            System.out.println((short)ch4);
            
}

    }


/*
JVM:  executes the bytecode generated by the compiler.
Bytecode: The Javac compiler of JDK compiles the Java source code into bytecode so that it can be executed by JVM.
JDK: Itis a complete Java development kit that includes everything including compiler, Java Runtime Environment (JRE), java debuggers, java docs, etc.
JRE: allows the Java program to run, however, we cannot compile it.
Garbage Collector: To delete or recollect that memory JVM has a program called Garbage Collector.
Finalize method: thisfunction is triggered by the garbage collector just before an object is deleted or destroyed.
*/


    
